# 配置参数优先级：jvm参数 > xml配置 > application.yml / application.properties
dubbo:
  application:
    name: boot-order-service-consumer
    parameters:
      qos:
        enable: true
        port: 22222
        accept:
          foreign:
            ip: true
  registry:
    address: zookeeper.kingsley.com:2181
    protocol: zookeeper

server:
  port: 8081