# 配置参数优先级：jvm参数 > xml配置 > application.yml / application.properties
dubbo:
  application:
    name: boot-user-service-provider
    parameters:
      qos:
        enable: true
        port: 22223
        accept:
          foreign:
            ip: true

  registry:
    address: zookeeper.kingsley.com:2181
    protocol: zookeeper

  protocol:
    name: dubbo
    port: 20881

  metadata-report:
    address: zookeeper://zookeeper.kingsley.com:2181
spring:
  main:
    allow-bean-definition-overriding: true